### Pytorch Basics

In [11]:
#imports
import torch
import numpy as np

In [6]:
#tensors
x = torch.tensor([1,2,3])
print(x)
print(x.size())

tensor([1, 2, 3])
torch.Size([3])


In [30]:
x = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
x

tensor([1., 2., 3.])

In [31]:
torch.arange(1,20,2)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [32]:
torch.randn(2,2)

tensor([[ 0.3197, -0.8935],
        [-0.8013,  1.3041]])

In [40]:
x = torch.arange(1,7)
reshaped = x.view(3,2)
reshaped

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [47]:
#Squeeze and unsqueeze
# squeeze: Removes dimensions of size 1.
# unsqueeze: Adds dimensions of size 1.

x = torch.tensor([[[1], [2], [3]]])  #size (1,3,1)
sq = x.unsqueeze(1)
sq.size()


torch.Size([1, 1, 3, 1])

In [8]:
#zeros
x = torch.zeros(3,3)
y = torch.ones(2,2)
x.size()

torch.Size([3, 3])

In [9]:
#randon
x = torch.rand(3,3)
x

tensor([[0.8100, 0.1417, 0.7345],
        [0.5485, 0.2076, 0.2105],
        [0.5483, 0.0683, 0.0374]])

In [13]:
np_arr = np.array([1,2,3])
torch_arr = torch.from_numpy(np_arr)
torch_arr

tensor([1, 2, 3], dtype=torch.int32)

In [14]:
if torch.cuda.is_available():
    x = x.cuda()  # Moves tensor to GPU

In [15]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

sum_ab = a + b  # Element-wise addition
diff_ab = a - b  # Element-wise subtraction
prod_ab = a * b  # Element-wise multiplication

In [16]:
a = torch.randn(3, 2)
b = torch.randn(2, 3)
result = torch.matmul(a, b)  # Matrix multiplication
result

tensor([[-0.0375, -0.2003,  0.1543],
        [ 0.1462,  0.9435, -0.5823],
        [ 0.0756,  0.6102, -0.2869]])

In [17]:
a@b

tensor([[-0.0375, -0.2003,  0.1543],
        [ 0.1462,  0.9435, -0.5823],
        [ 0.0756,  0.6102, -0.2869]])

In [26]:
x = torch.tensor([1.0, 2.0], requires_grad=True)
y = x * 2
z = y.sum()

In [28]:
z.backward()

In [29]:
x.grad

tensor([2., 2.])

In [23]:
x_detached = x.detach() 
x_detached

tensor([1., 2.])

In [49]:
x = torch.rand(2, 3)  # Shape: (2, 3)
transposed = x.transpose(0, 1)  # Shape: (3, 2)
transposed.size()

torch.Size([3, 2])

In [53]:

#indexing and slicing 
x = torch.tensor([[1, 2, 3,4,5, 6], [4, 5, 6, 7, 8, 9]])

print(x[0, 2])   # Element at row 0, column 2
print(x[:, 1])   # All rows, column 1
print(x[1, :])   # Row 1, all columns

tensor(3)
tensor([2, 5])
tensor([4, 5, 6, 7, 8, 9])


In [55]:
x[:, 0::2]

tensor([[1, 3, 5],
        [4, 6, 8]])

In [56]:
x = torch.arange(9).reshape(3, 3)

print(x[[0, 2]])    # Select rows 0 and 2
print(x[x > 5])     # Select elements greater than 5

tensor([[0, 1, 2],
        [6, 7, 8]])
tensor([6, 7, 8])


In [57]:
x = torch.rand(2, 3, 4)  # Shape: (2, 3, 4)
print("Original Shape:", x.shape)

transposed = torch.transpose(x, 1, 2)  # Swap dimensions 1 and 2
print("Transposed Shape:", transposed.shape)

Original Shape: torch.Size([2, 3, 4])
Transposed Shape: torch.Size([2, 4, 3])
